// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace Hello_Mac
{
	public partial class FollowDialogController : NSViewController
	{
		public FollowDialogController (IntPtr handle) : base (handle)
		{
		}
		#region Private Methods
		private void CloseDialog()
		{
			this.View.Window.Close();
		}
		#endregion
		#region Custom Actions
		partial void AcceptDialog(Foundation.NSObject sender)
		{
			CloseDialog();
			RaiseDialogAccepted();
		}

		partial void CancelDialog(Foundation.NSObject sender)
		{
			CloseDialog();
			RaiseDialogCanceled();
		}
		#endregion

		#region Events
		public EventHandler DialogAccepted;

		internal void RaiseDialogAccepted()
		{
			if (this.DialogAccepted != null)
				this.DialogAccepted(this, EventArgs.Empty);
		}

		public EventHandler DialogCanceled;

		internal void RaiseDialogCanceled()
		{
			if (this.DialogCanceled != null)
				this.DialogCanceled(this, EventArgs.Empty);
		}
		#endregion

		public override void AwakeFromNib()
		{
			base.AwakeFromNib();

			var FollowListDataSource = new MyListDataSource();
			FollowListDataSource.ListItems.Add(new MyListItem("相互フォローリスト"));
			FollowListDataSource.ListItems.Add(new MyListItem("フォロワー1", "https://randomuser.me/api/portraits/men/1.jpg"));
			FollowListDataSource.ListItems.Add(new MyListItem("フォロワー2", "https://randomuser.me/api/portraits/men/2.jpg"));
			FollowListDataSource.ListItems.Add(new MyListItem("フォロワー3", "https://randomuser.me/api/portraits/men/3.jpg"));
			FollowListDataSource.ListItems.Add(new MyListItem("フォロワー4", "https://randomuser.me/api/portraits/men/4.jpg"));
			FollowListDataSource.ListItems.Add(new MyListItem("フォロワー5", "https://randomuser.me/api/portraits/men/5.jpg"));

			if (FollowList != null)
			{
				FollowList.DataSource = FollowListDataSource;
				FollowList.Delegate = new MyListDelegate(FollowListDataSource);
			}
		}
	}
}
