// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace Hello_Mac
{
	public partial class LoginDialogController : NSViewController
	{
		#region Private Variables
		private NSViewController _presentor;
		#endregion

		#region Application Access
		public static AppDelegate App
		{
			get { return (AppDelegate)NSApplication.SharedApplication.Delegate; }
		}
		#endregion

		#region Computed Properties
		public NSViewController Presentor
		{
			get { return _presentor; }
			set { _presentor = value; }
		}
		#endregion

		#region Constructors
		public LoginDialogController(IntPtr handle) : base(handle)
		{
		}
		#endregion

		#region Override Methods
		public override void ViewWillAppear()
		{
			base.ViewWillAppear();
		}
		#endregion

		#region Private Methods
		private void CloseDialog()
		{
			if (Presentor != null)
				Presentor.DismissViewController(this);
			this.DismissViewController(this);
		}
		#endregion

		#region Custom Actions
		partial void AcceptDialog(Foundation.NSObject sender)
		{
			RaiseDialogAccepted();
			CloseDialog();
		}

		partial void CancelDialog(Foundation.NSObject sender)
		{
			RaiseDialogCanceled();
			CloseDialog();
		}
		#endregion

		#region Events
		public EventHandler DialogAccepted;

		internal void RaiseDialogAccepted()
		{
			if (this.DialogAccepted != null)
				this.DialogAccepted(this, EventArgs.Empty);
		}

		public EventHandler DialogCanceled;

		internal void RaiseDialogCanceled()
		{
			if (this.DialogCanceled != null)
				this.DialogCanceled(this, EventArgs.Empty);
		}
		#endregion
	}
}
